### ISSUE TITLE
ACT navigation & banner is out of sync

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wai-minimal-header-design#101]
The ACT header was updated recently, changing the title, tag line, adding in a link. There is also now a navigation bar added with links to "All rules", "About" and "Implementations". These are available in the preview, but have not been copied over to the WAI website.

You can view the difference here:
- https://www.w3.org/WAI/standards-guidelines/act/rules/ (current)
- https://wai-wcag-act-rules.netlify.app/standards-guidelines/act/rules/ (expected)

Here's a screenshot of what the navigation should look:
![Screenshot of ACT Rules header and navigation bar](https://user-images.githubusercontent.com/530687/175922419-d3234124-d2e1-4013-b32f-fd2f53278d49.png)

The configuration for this can be found in the [_config.yml](https://github.com/w3c/wcag-act-rules/blob/master/_config.yml) file on the wcag-act-rules repo.

**Comment by SteveALee** [comment]
It appears both the repo and the wai-website _config files need to be updated to reflect the header and nav changes 

The current settings for the wai website config are

```yaml
      standalone_resource_header:
        title: WCAG 2 Test Rules
        subtitle: For developers of evaluation tools and test methodologies
        link:
          title: About WCAG 2 Test Rules
          ref: /standards-guidelines/act/rules/about/
      standalone_resource_pager:
        name: All Test Rules
        ref: /standards-guidelines/act/rules/
```

and the repo config are

```yaml
      standalone_resource_header:
        title: ACT Rules
        title-ref: /standards-guidelines/act/rules/
        subtitle: Rules for accessibility conformance testing (ACT)
      standalone_resource_nav_links:
        - name: All Rules
          ref: /standards-guidelines/act/rules/
        - name: About
          ref: /standards-guidelines/act/rules/about/
        - name: Implementations
          ref: /standards-guidelines/act/implementations/
```

I believe the correct settings for both is now:

```yaml
      standalone_resource_header:
        title: ACT Rules
        subtitle: Rules for accessibility conformance testing (ACT)
        link:
          title: About Act Rules
          ref: /standards-guidelines/act/rules/about/
      standalone_resource_nav_links:
        - name: All Rules
          ref: /standards-guidelines/act/rules/
        - name: About
          ref: /standards-guidelines/act/rules/about/
        - name: Implementations
          ref: /standards-guidelines/act/implementations/
```

This provides both the link to About in the header and the nav

@WilcoFiers @shawna-slh please confirm
